# -*- coding: utf-8 -*-
"""swieta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xg-f5j7Gy32bLT1FB6wjQIGnMEFRwNS0
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

def narysuj_mikolaja():
    """Rysuje geometryczną reprezentację Świętego Mikołaja."""

    # 1. Konfiguracja wykresu (Zwracamy fig i ax)
    fig, ax = plt.subplots(figsize=(6, 9))

    # Ustawienie limitów osi i proporcji
    ax.set_xlim(-5, 5)
    ax.set_ylim(-9.5, 4)
    ax.set_aspect('equal')
    ax.axis('off') # Ukrycie osi

    # Definicja kolorów
    C_RED = '#C60C0C'
    C_WHITE = '#EEEEEE'
    C_SKIN = '#FEEBC9'
    C_BLACK = '#212121'
    C_GOLD = '#FFD700'

    # --- Rysowanie elementów (Zorder 0 to tył) ---

    # 2. Ciało (Duży Czerwony Owal)
    cialo = patches.Ellipse((0, -3.0), 4.5, 6.0, color=C_RED, zorder=0)
    ax.add_patch(cialo)

    # 3. Nogi i Buty
    noga_l = patches.Rectangle((-1.5, -9), 1.0, 3.5, color=C_RED, zorder=1)
    noga_p = patches.Rectangle((0.5, -9), 1.0, 3.5, color=C_RED, zorder=1)
    ax.add_patch(noga_l)
    ax.add_patch(noga_p)

    but_l = patches.Rectangle((-1.8, -9.5), 1.6, 0.5, color=C_BLACK, zorder=2)
    but_p = patches.Rectangle((0.2, -9.5), 1.6, 0.5, color=C_BLACK, zorder=2)
    ax.add_patch(but_l)
    ax.add_patch(but_p)

    # 4. Ręce
    reka_l = patches.Rectangle((-3.5, -4.0), 1.5, 1.5, color=C_RED, zorder=3)
    reka_p = patches.Rectangle((2.0, -4.0), 1.5, 1.5, color=C_RED, zorder=3)
    ax.add_patch(reka_l)
    ax.add_patch(reka_p)

    mankiet_l = patches.Rectangle((-3.5, -4.0), 1.5, 0.5, color=C_WHITE, zorder=4)
    mankiet_p = patches.Rectangle((2.0, -4.0), 1.5, 0.5, color=C_WHITE, zorder=4)
    ax.add_patch(mankiet_l)
    ax.add_patch(mankiet_p)

    dlonia_l = patches.Circle((-2.75, -4.0), 0.4, color=C_BLACK, zorder=5)
    dlonia_p = patches.Circle((2.75, -4.0), 0.4, color=C_BLACK, zorder=5)
    ax.add_patch(dlonia_l)
    ax.add_patch(dlonia_p)

    # 5. Pas i Klamra
    pas = patches.Rectangle((-3.0, -4.5), 6, 1.0, color=C_BLACK, zorder=6)
    ax.add_patch(pas)

    klamra = patches.Rectangle((-0.7, -4.3), 1.4, 0.6, color=C_GOLD, zorder=7)
    klamra_wew = patches.Rectangle((-0.5, -4.1), 1.0, 0.2, color=C_BLACK, zorder=8)
    ax.add_patch(klamra)
    ax.add_patch(klamra_wew)

    # 6. Broda i Wąsy
    broda_podstawa = patches.Arc((0, -0.5), 4.0, 3.5, angle=0, theta1=0, theta2=180,
                                 color=C_WHITE, linewidth=15, solid_capstyle='round', zorder=9)
    ax.add_patch(broda_podstawa)

    was = patches.Arc((0, -0.1), 3.0, 1.5, angle=0, theta1=0, theta2=180,
                      color=C_WHITE, linewidth=10, solid_capstyle='round', zorder=10)
    ax.add_patch(was)

    # 7. Czapka
    futerko_czapki = patches.Rectangle((-2.5, 1.2), 5, 0.6, color=C_WHITE, zorder=11)
    ax.add_patch(futerko_czapki)

    czapka_x = np.array([-2.0, 0.5, 3.0])
    czapka_y = np.array([1.5, 3.5, 1.5])
    czapka = patches.Polygon(list(zip(czapka_x, czapka_y)), closed=True, color=C_RED, zorder=12)
    ax.add_patch(czapka)

    pompon = patches.Circle((0.5, 3.5), 0.5, color=C_WHITE, zorder=13)
    ax.add_patch(pompon)

    # 8. GŁOWA I TWARZ (Najwyższy ZORDER)
    glowa = patches.Circle((0, 0), 1.5, color=C_SKIN, zorder=14)
    ax.add_patch(glowa)

    nos = patches.Circle((0, 0.3), 0.3, color='#F06292', zorder=15)
    ax.add_patch(nos)

    lewe_oko = patches.Circle((-0.7, 0.8), 0.15, color=C_BLACK, zorder=16)
    prawe_oko = patches.Circle((0.7, 0.8), 0.15, color=C_BLACK, zorder=16)
    ax.add_patch(lewe_oko)
    ax.add_patch(prawe_oko)

    ax.set_title('Święty Mikołaj w Matplotlib', fontsize=16, color=C_RED)

    # Zwrócenie obiektu figury Matplotlib
    return fig

# --- Główna funkcja Streamlit ---

def main():
    st.title("🎅 Generator Świętego Mikołaja (Streamlit)")
    st.write("Aplikacja wyświetla postać Mikołaja wygenerowaną za pomocą geometrycznych kształtów Matplotlib.")

    # Wywołanie funkcji rysującej
    figura_mikolaja = narysuj_mikolaja()

    # Wyświetlenie figury Matplotlib w Streamlit
    st.pyplot(figura_mikolaja)

if __name__ == "__main__":
    main()